import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Homepage() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h1>Welcome to my events app</h1>
		</div>
	);
}
